language: node_js
node_js:
- '5'
- '4'
- '0.12'
- '0.10'
sudo: false
before_install:
- npm -g install npm@latest
script:
- npm run test
after_success:
- npm run codecov
deploy:
  provider: npm
  email: git@jwr.vc
  api_key:
    secure: K/+dVjtCqesr5E5EMZo/qBdKlWwPpZ60yp1GtKoAhSZUtL4VY4A8LOJmcSeIeYvsPkK8PRSCyb2FTDfSTYEO4dWVfNPoLxWp7U48iIiHSfLdNixfTiBHyjdKdP/6oCz3TNfb9upPUb1lcb5h+rM2KJgCLT6s30Vbajka6STeDCs=
  on:
    tags: true
    repo: jamesramsay/through2-get
