language: node_js
node_js:
  - '5'
  - '4'
cache:
  directories:
  - node_modules
sudo: false
before_install:
- npm -g install npm@latest
script:
- npm run test
after_success:
- npm run codecov
deploy:
  provider: npm
  email: git@jwr.vc
  api_key:
    secure: miMXdvr3agM9ul2+Tr/WtClWPMQ4PD9teddYDSF0WsPYaf6SXEEqUtQnGcQmPt4+JpZx7ssTUdSxQdlcswYmSoVcg2QafG8BzO/TpPnZXJ0W6bGbMQ0d6dNceui4ZVGsPAhNV2oh5wjd5iWMw1nYY/ZcWd0K8JL2Ps8UXUWNCj5ErHIju8MR9aBSLz2ZDH+4jrbCAxvsz9oZ9JwKx6dtu+f5kdzTz1AJpc7FAyO2EwBNHVItWHwqcANBtXnBh3X15dFkwZxSPAeX31Ibnrnb0/PHsYjhirGsK7PHw40I43B+R8KR2whSgp65hhOh9fI+MgaAD3dbNpGsjcb7vrFthiaiA+QLxEtj3utwIW39IgnI/ns3/VM24Wn3w/m5NuiuFKxRWfDoNGAw0eBg5GsG1O+AiX7IwlRPQhJ2iErwXpSyLk9mMG2s9lOq207h8YWzyvM+wYLZ+ujraTsDTDTiH+QN51xnVZXdNoJcF1kckQvRN26RlJnTv6wvvTHilyYKqsQpGiB1EdOFg+3SlsGbo5re+okHlVLy502r1YeQfeC7Mr4ZKU7d6XfStj8cL9K5wDi/Fy29yJI6TPOLuuTGYJodB8TgdDUwlZzoWrypamt26a9/XZ+pWMcegCJVL34rr8FgH0a22r4QqPjbz/Ah4Nklxi3YBtk6mRbN1ur0eNE=
  on:
    tags: true
    repo: jamesramsay/through2-get
